version: "3"
volumes:
  vendor-store:
services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build: ./docker/app
    volumes:
      - ../source:/var/www/html
      - vendor-store:/var/www/html/vendor
  nginx:
    image: nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - 8082:80
      - 4432:443
    volumes:
      - ../source/public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/localhost-key.pem:/etc/nginx/certs/server.key
      - ./docker/nginx/localhost.pem:/etc/nginx/certs/server.crt
    depends_on:
      - app
